# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Software\cmake-3.31.4-windows-x86_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Software\cmake-3.31.4-windows-x86_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Alexsander\Desktop\Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Alexsander\Desktop\Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Software\cmake-3.31.4-windows-x86_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Software\cmake-3.31.4-windows-x86_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Alexsander\Desktop\Project\CMakeFiles C:\Users\Alexsander\Desktop\Project\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Alexsander\Desktop\Project\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named main_autogen_timestamp_deps

# Build rule for target.
main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main_autogen_timestamp_deps
.PHONY : main_autogen_timestamp_deps

# fast build rule for target.
main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main_autogen_timestamp_deps.dir\build.make CMakeFiles/main_autogen_timestamp_deps.dir/build
.PHONY : main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named main_autogen

# Build rule for target.
main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main_autogen
.PHONY : main_autogen

# fast build rule for target.
main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main_autogen.dir\build.make CMakeFiles/main_autogen.dir/build
.PHONY : main_autogen/fast

main_autogen/mocs_compilation.obj: main_autogen/mocs_compilation.cpp.obj
.PHONY : main_autogen/mocs_compilation.obj

# target to build an object file
main_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.obj
.PHONY : main_autogen/mocs_compilation.cpp.obj

main_autogen/mocs_compilation.i: main_autogen/mocs_compilation.cpp.i
.PHONY : main_autogen/mocs_compilation.i

# target to preprocess a source file
main_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.i
.PHONY : main_autogen/mocs_compilation.cpp.i

main_autogen/mocs_compilation.s: main_autogen/mocs_compilation.cpp.s
.PHONY : main_autogen/mocs_compilation.s

# target to generate assembly for a file
main_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.s
.PHONY : main_autogen/mocs_compilation.cpp.s

qrc_styles.obj: qrc_styles.cpp.obj
.PHONY : qrc_styles.obj

# target to build an object file
qrc_styles.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/qrc_styles.cpp.obj
.PHONY : qrc_styles.cpp.obj

qrc_styles.i: qrc_styles.cpp.i
.PHONY : qrc_styles.i

# target to preprocess a source file
qrc_styles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/qrc_styles.cpp.i
.PHONY : qrc_styles.cpp.i

qrc_styles.s: qrc_styles.cpp.s
.PHONY : qrc_styles.s

# target to generate assembly for a file
qrc_styles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/qrc_styles.cpp.s
.PHONY : qrc_styles.cpp.s

src/Classes/Item.obj: src/Classes/Item.cpp.obj
.PHONY : src/Classes/Item.obj

# target to build an object file
src/Classes/Item.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Classes/Item.cpp.obj
.PHONY : src/Classes/Item.cpp.obj

src/Classes/Item.i: src/Classes/Item.cpp.i
.PHONY : src/Classes/Item.i

# target to preprocess a source file
src/Classes/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Classes/Item.cpp.i
.PHONY : src/Classes/Item.cpp.i

src/Classes/Item.s: src/Classes/Item.cpp.s
.PHONY : src/Classes/Item.s

# target to generate assembly for a file
src/Classes/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Classes/Item.cpp.s
.PHONY : src/Classes/Item.cpp.s

src/Functions/DatabaseFunctions.obj: src/Functions/DatabaseFunctions.cpp.obj
.PHONY : src/Functions/DatabaseFunctions.obj

# target to build an object file
src/Functions/DatabaseFunctions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/DatabaseFunctions.cpp.obj
.PHONY : src/Functions/DatabaseFunctions.cpp.obj

src/Functions/DatabaseFunctions.i: src/Functions/DatabaseFunctions.cpp.i
.PHONY : src/Functions/DatabaseFunctions.i

# target to preprocess a source file
src/Functions/DatabaseFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/DatabaseFunctions.cpp.i
.PHONY : src/Functions/DatabaseFunctions.cpp.i

src/Functions/DatabaseFunctions.s: src/Functions/DatabaseFunctions.cpp.s
.PHONY : src/Functions/DatabaseFunctions.s

# target to generate assembly for a file
src/Functions/DatabaseFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/DatabaseFunctions.cpp.s
.PHONY : src/Functions/DatabaseFunctions.cpp.s

src/Functions/mainFileFunctions.obj: src/Functions/mainFileFunctions.cpp.obj
.PHONY : src/Functions/mainFileFunctions.obj

# target to build an object file
src/Functions/mainFileFunctions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/mainFileFunctions.cpp.obj
.PHONY : src/Functions/mainFileFunctions.cpp.obj

src/Functions/mainFileFunctions.i: src/Functions/mainFileFunctions.cpp.i
.PHONY : src/Functions/mainFileFunctions.i

# target to preprocess a source file
src/Functions/mainFileFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/mainFileFunctions.cpp.i
.PHONY : src/Functions/mainFileFunctions.cpp.i

src/Functions/mainFileFunctions.s: src/Functions/mainFileFunctions.cpp.s
.PHONY : src/Functions/mainFileFunctions.s

# target to generate assembly for a file
src/Functions/mainFileFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Functions/mainFileFunctions.cpp.s
.PHONY : src/Functions/mainFileFunctions.cpp.s

src/Interfaces/MainWindow.obj: src/Interfaces/MainWindow.cpp.obj
.PHONY : src/Interfaces/MainWindow.obj

# target to build an object file
src/Interfaces/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Interfaces/MainWindow.cpp.obj
.PHONY : src/Interfaces/MainWindow.cpp.obj

src/Interfaces/MainWindow.i: src/Interfaces/MainWindow.cpp.i
.PHONY : src/Interfaces/MainWindow.i

# target to preprocess a source file
src/Interfaces/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Interfaces/MainWindow.cpp.i
.PHONY : src/Interfaces/MainWindow.cpp.i

src/Interfaces/MainWindow.s: src/Interfaces/MainWindow.cpp.s
.PHONY : src/Interfaces/MainWindow.s

# target to generate assembly for a file
src/Interfaces/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Interfaces/MainWindow.cpp.s
.PHONY : src/Interfaces/MainWindow.cpp.s

src/Widgets/ItemCard/InformationHolder.obj: src/Widgets/ItemCard/InformationHolder.cpp.obj
.PHONY : src/Widgets/ItemCard/InformationHolder.obj

# target to build an object file
src/Widgets/ItemCard/InformationHolder.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/InformationHolder.cpp.obj
.PHONY : src/Widgets/ItemCard/InformationHolder.cpp.obj

src/Widgets/ItemCard/InformationHolder.i: src/Widgets/ItemCard/InformationHolder.cpp.i
.PHONY : src/Widgets/ItemCard/InformationHolder.i

# target to preprocess a source file
src/Widgets/ItemCard/InformationHolder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/InformationHolder.cpp.i
.PHONY : src/Widgets/ItemCard/InformationHolder.cpp.i

src/Widgets/ItemCard/InformationHolder.s: src/Widgets/ItemCard/InformationHolder.cpp.s
.PHONY : src/Widgets/ItemCard/InformationHolder.s

# target to generate assembly for a file
src/Widgets/ItemCard/InformationHolder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/InformationHolder.cpp.s
.PHONY : src/Widgets/ItemCard/InformationHolder.cpp.s

src/Widgets/ItemCard/ItemCard.obj: src/Widgets/ItemCard/ItemCard.cpp.obj
.PHONY : src/Widgets/ItemCard/ItemCard.obj

# target to build an object file
src/Widgets/ItemCard/ItemCard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/ItemCard.cpp.obj
.PHONY : src/Widgets/ItemCard/ItemCard.cpp.obj

src/Widgets/ItemCard/ItemCard.i: src/Widgets/ItemCard/ItemCard.cpp.i
.PHONY : src/Widgets/ItemCard/ItemCard.i

# target to preprocess a source file
src/Widgets/ItemCard/ItemCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/ItemCard.cpp.i
.PHONY : src/Widgets/ItemCard/ItemCard.cpp.i

src/Widgets/ItemCard/ItemCard.s: src/Widgets/ItemCard/ItemCard.cpp.s
.PHONY : src/Widgets/ItemCard/ItemCard.s

# target to generate assembly for a file
src/Widgets/ItemCard/ItemCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/ItemCard.cpp.s
.PHONY : src/Widgets/ItemCard/ItemCard.cpp.s

src/Widgets/ItemCard/Transparent2DLayer.obj: src/Widgets/ItemCard/Transparent2DLayer.cpp.obj
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.obj

# target to build an object file
src/Widgets/ItemCard/Transparent2DLayer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/Transparent2DLayer.cpp.obj
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.cpp.obj

src/Widgets/ItemCard/Transparent2DLayer.i: src/Widgets/ItemCard/Transparent2DLayer.cpp.i
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.i

# target to preprocess a source file
src/Widgets/ItemCard/Transparent2DLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/Transparent2DLayer.cpp.i
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.cpp.i

src/Widgets/ItemCard/Transparent2DLayer.s: src/Widgets/ItemCard/Transparent2DLayer.cpp.s
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.s

# target to generate assembly for a file
src/Widgets/ItemCard/Transparent2DLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/ItemCard/Transparent2DLayer.cpp.s
.PHONY : src/Widgets/ItemCard/Transparent2DLayer.cpp.s

src/Widgets/WindowCard/HorizontalScrollArea.obj: src/Widgets/WindowCard/HorizontalScrollArea.cpp.obj
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.obj

# target to build an object file
src/Widgets/WindowCard/HorizontalScrollArea.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/HorizontalScrollArea.cpp.obj
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.cpp.obj

src/Widgets/WindowCard/HorizontalScrollArea.i: src/Widgets/WindowCard/HorizontalScrollArea.cpp.i
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.i

# target to preprocess a source file
src/Widgets/WindowCard/HorizontalScrollArea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/HorizontalScrollArea.cpp.i
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.cpp.i

src/Widgets/WindowCard/HorizontalScrollArea.s: src/Widgets/WindowCard/HorizontalScrollArea.cpp.s
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.s

# target to generate assembly for a file
src/Widgets/WindowCard/HorizontalScrollArea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/HorizontalScrollArea.cpp.s
.PHONY : src/Widgets/WindowCard/HorizontalScrollArea.cpp.s

src/Widgets/WindowCard/InventoryCard.obj: src/Widgets/WindowCard/InventoryCard.cpp.obj
.PHONY : src/Widgets/WindowCard/InventoryCard.obj

# target to build an object file
src/Widgets/WindowCard/InventoryCard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/InventoryCard.cpp.obj
.PHONY : src/Widgets/WindowCard/InventoryCard.cpp.obj

src/Widgets/WindowCard/InventoryCard.i: src/Widgets/WindowCard/InventoryCard.cpp.i
.PHONY : src/Widgets/WindowCard/InventoryCard.i

# target to preprocess a source file
src/Widgets/WindowCard/InventoryCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/InventoryCard.cpp.i
.PHONY : src/Widgets/WindowCard/InventoryCard.cpp.i

src/Widgets/WindowCard/InventoryCard.s: src/Widgets/WindowCard/InventoryCard.cpp.s
.PHONY : src/Widgets/WindowCard/InventoryCard.s

# target to generate assembly for a file
src/Widgets/WindowCard/InventoryCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/InventoryCard.cpp.s
.PHONY : src/Widgets/WindowCard/InventoryCard.cpp.s

src/Widgets/WindowCard/OriginalCard.obj: src/Widgets/WindowCard/OriginalCard.cpp.obj
.PHONY : src/Widgets/WindowCard/OriginalCard.obj

# target to build an object file
src/Widgets/WindowCard/OriginalCard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/OriginalCard.cpp.obj
.PHONY : src/Widgets/WindowCard/OriginalCard.cpp.obj

src/Widgets/WindowCard/OriginalCard.i: src/Widgets/WindowCard/OriginalCard.cpp.i
.PHONY : src/Widgets/WindowCard/OriginalCard.i

# target to preprocess a source file
src/Widgets/WindowCard/OriginalCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/OriginalCard.cpp.i
.PHONY : src/Widgets/WindowCard/OriginalCard.cpp.i

src/Widgets/WindowCard/OriginalCard.s: src/Widgets/WindowCard/OriginalCard.cpp.s
.PHONY : src/Widgets/WindowCard/OriginalCard.s

# target to generate assembly for a file
src/Widgets/WindowCard/OriginalCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/Widgets/WindowCard/OriginalCard.cpp.s
.PHONY : src/Widgets/WindowCard/OriginalCard.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... main_autogen
	@echo ... main_autogen_timestamp_deps
	@echo ... main
	@echo ... main_autogen/mocs_compilation.obj
	@echo ... main_autogen/mocs_compilation.i
	@echo ... main_autogen/mocs_compilation.s
	@echo ... qrc_styles.obj
	@echo ... qrc_styles.i
	@echo ... qrc_styles.s
	@echo ... src/Classes/Item.obj
	@echo ... src/Classes/Item.i
	@echo ... src/Classes/Item.s
	@echo ... src/Functions/DatabaseFunctions.obj
	@echo ... src/Functions/DatabaseFunctions.i
	@echo ... src/Functions/DatabaseFunctions.s
	@echo ... src/Functions/mainFileFunctions.obj
	@echo ... src/Functions/mainFileFunctions.i
	@echo ... src/Functions/mainFileFunctions.s
	@echo ... src/Interfaces/MainWindow.obj
	@echo ... src/Interfaces/MainWindow.i
	@echo ... src/Interfaces/MainWindow.s
	@echo ... src/Widgets/ItemCard/InformationHolder.obj
	@echo ... src/Widgets/ItemCard/InformationHolder.i
	@echo ... src/Widgets/ItemCard/InformationHolder.s
	@echo ... src/Widgets/ItemCard/ItemCard.obj
	@echo ... src/Widgets/ItemCard/ItemCard.i
	@echo ... src/Widgets/ItemCard/ItemCard.s
	@echo ... src/Widgets/ItemCard/Transparent2DLayer.obj
	@echo ... src/Widgets/ItemCard/Transparent2DLayer.i
	@echo ... src/Widgets/ItemCard/Transparent2DLayer.s
	@echo ... src/Widgets/WindowCard/HorizontalScrollArea.obj
	@echo ... src/Widgets/WindowCard/HorizontalScrollArea.i
	@echo ... src/Widgets/WindowCard/HorizontalScrollArea.s
	@echo ... src/Widgets/WindowCard/InventoryCard.obj
	@echo ... src/Widgets/WindowCard/InventoryCard.i
	@echo ... src/Widgets/WindowCard/InventoryCard.s
	@echo ... src/Widgets/WindowCard/OriginalCard.obj
	@echo ... src/Widgets/WindowCard/OriginalCard.i
	@echo ... src/Widgets/WindowCard/OriginalCard.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

